name: Build & Push Docker Image

on:
    push:
        branches:
            - main  # Se ejecuta solo cuando se mergea a main
    workflow_dispatch:
        
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write  # Necesario para publicar en GitHub Container Registry

        steps:
            - uses: actions/checkout@v4

            - uses: docker/setup-buildx-action@v3 # Acci칩n oficial para construir y publicar im치genes Docker

            - uses: docker/login-action@v3  # Acci칩n oficial para iniciar sesi칩n en Docker
              with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            - id: meta
              uses: docker/metadata-action@v5
              with:
                    images: ${{env.REGISTRY}}/${{ env.IMAGE_NAME }}
                    tags: |
                        type=ref,event=branch
                        type=sha,prefix={{branch}}-
                        type=raw,value=latest,enable={{is_default_branch}}

            - uses: docker/build-push-action@v5
              with:
                    context: .
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max